

spring:
    datasource:  
        url: jdbc:h2:mem:azhar
        driverClassName: org.h2.Driver
        username: syed
        password: azhar


    jpa: 
         show-sql: true
    h2:
         console:
             enabled:  true
          